plugin: amazon.aws.aws_ec2
regions:
  - us-east-2
filters:
  tag:Project: env0-ansible-demo
  instance-state-name: running
keyed_groups:
  - key: tags.Role
    prefix: ""
    separator: ""
hostnames:
  - instance-id
compose:
  ansible_host: instance_id
  ansible_connection: community.aws.aws_ssm
  ansible_aws_ssm_region: placement.region
